build:
  version: "3.0"

selfservice:
  message: "Welcome to Self Service API related QA APIs "
  contactDetails:
    name: "Syed - QA Lead"
    email: "s.siddik2709@gmail.com"
  onCallSupport:
    - 8522002553