build:
  version: "1.0"

selfservice:
  message: "Welcome to self service related local APIs "
  contactDetails:
    name: "Syed - Developer"
    email: "s.siddik2709@gmail.com"
  onCallSupport:
    - 8522002553

